apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    name: postgres-db
    app: voting-app
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    imagePullPolicy: IfNotPresent
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name:  POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    ports:
     - containerPort: 5432
