apiVersion: v1
kind: Pod
metadata:
  name: redis-app
  labels:
    name: redis-app
    app: voting-app
spec:
  containers:
  - name: redis
    image: redis:latest
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 6379
