apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    name: vote-app
    app: voting-app

