apiVersion: v1
kind: Pod
metadata:
  name: vote-app
  labels:
    name: vote-app
    app: voting-app
spec:
  containers:
    - name: vote-app
      image: aneesravidkhan/votingapp_vote:v1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
