apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: worker-app
    app: voting-app
spec:
  containers:
  - name: worker-app
    image: aneesravidkhan/votingapp_worker:v1.0
    imagePullPolicy: IfNotPresent
